---
- name: Refresh Token for Automation Hub
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    sat_org: "satsrv01"
    sat_org: "MyOrg"
    sat_hc: "MyHC"
    sat_hosts:
      - plasrv01.local
      - pldsrv01.local
      - plusrv01.local

  tasks:
    - name: Print token
      ansible.builtin.debug:
        msg: |
          "This is my token:"
          "{{ console_token }}"

